# BetterSpawns v1.0.2
# This config will work with versions 0.1.3 up until at least 1.0.2

# Players will not be teleported to any location where they would be positioned on the following blocks:
unsafe-ground-blocks:
  - LAVA
  - WATER
  - MAGMA_BLOCK
  - CACTUS
  - FIRE
  - CAMPFIRE
  - SOUL_FIRE
  - SOUL_CAMPFIRE
  - OAK_LEAVES
  - SPRUCE_LEAVES
  - BIRCH_LEAVES
  - JUNGLE_LEAVES
  - ACACIA_LEAVES
  - DARK_OAK_LEAVES
  - MANGROVE_LEAVES
  - CHERRY_LEAVES
  - AZALEA_LEAVES
  - FLOWERING_AZALEA_LEAVES
  - AZALEA_LEAVES_FLOWERED

# The message sent to the player after using /play
play-message: "&aTeleporting you to a random location..."

# The world border radius (in blocks) used for random spawn locations.
# This is HALF of the total world width/length.
# Example: a 1250x1250 world = radius of 625.
spawn-radius: 625